include: https://gitlab-templates.ddbuild.io/compute-delivery/v2/compute-delivery.yml

# test:
#   stage: verify
#   tags: [ "arch:amd64" ]
#   image: registry.ddbuild.io/images/mirror/golang:1.21.1
#   script:
#     - make test

build-docker-image:
  extends:
  - .build-docker-image
  only:
    - branches
  timeout: 6h
  variables:
    IMAGE_NAME: cloud-controller-manager/aws
    BUILDER_IMAGE: "images/mirror/golang:1.21"
    IMAGE_TAG: v0.0.1-alpha.1
    PLATFORMS: "linux/arm64/v8"
  script:
  - METADATA_FILE=$(mktemp)
  - docker buildx build --platform "linux/arm64/v8" --tag registry.ddbuild.io/$IMAGE_NAME:$IMAGE_TAG --build-arg="BUILDER_IMAGE=registry.ddbuild.io/images/mirror/golang:1.21" --build-arg="BASE_IMAGE=registry.ddbuild.io/images/base/gbi-$BASE_IMAGE:release" --label target=prod $EXTRA_ARGS --push --metadata-file ${METADATA_FILE} "$CONTEXT_DIR"


run-campaign:
  variables:
    CHART_NAME: k8s-platform-k8s-cloud-controller-manager
    COMPONENT: aws-cloud-controller-manager
    SLACK_CHANNEL: compute-ops
  extends: .run-campaign
